// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class BocothngTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void bocothng() {
    driver.Navigate().GoToUrl("http://localhost:3000/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.CssSelector("div > .menu-bars > svg")).Click();
    {
      var element = driver.FindElement(By.LinkText("LẬP BÁO CÁO"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.LinkText("LẬP BÁO CÁO"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.LinkText("LẬP BÁO CÁO"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.LinkText("LẬP BÁO CÁO")).Click();
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).SendKeys("2024-06");
    driver.FindElement(By.CssSelector(".form-select")).Click();
    {
      var dropdown = driver.FindElement(By.CssSelector(".form-select"));
      dropdown.FindElement(By.XPath("//option[. = 'Tồn Sách']")).Click();
    }
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.CssSelector(".print")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".print"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".form-select")).Click();
    {
      var dropdown = driver.FindElement(By.CssSelector(".form-select"));
      dropdown.FindElement(By.XPath("//option[. = 'Công Nợ']")).Click();
    }
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".print")).Click();
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).SendKeys("2024-12");
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.CssSelector(".Toastify__toast-body")).Click();
  }
}
