// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class QunlbnschTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void qunlbnsch() {
    driver.Navigate().GoToUrl("http://localhost:3000/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.CssSelector("div > .menu-bars > svg")).Click();
    driver.FindElement(By.LinkText("QUẢN LÝ BÁN SÁCH")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(1) > .form-control")).SendKeys("2024-07-06");
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(2) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(2) > .form-control")).SendKeys("0987654321\`");
    driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control")).SendKeys("Truyện Kiều");
    driver.FindElement(By.CssSelector(".cthd-container .col-6:nth-child(2) > .form-control")).SendKeys("10");
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(2) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(2) > .form-control")).SendKeys("0987654321");
    driver.FindElement(By.CssSelector(".btn-add")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-add"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".money .form-control")).Click();
    driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control")).SendKeys("Đắc Nhân Tâm");
    driver.FindElement(By.CssSelector(".cthd-container .col-6:nth-child(2) > .form-control")).SendKeys("100");
    driver.FindElement(By.CssSelector(".btn-add")).Click();
    driver.FindElement(By.CssSelector(".Toastify__toast-body")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".modal")).Click();
    driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control")).SendKeys("Thủy Hử");
    driver.FindElement(By.CssSelector(".cthd-container .col-6:nth-child(2) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".cthd-container .col-6:nth-child(2) > .form-control")).SendKeys("10");
    driver.FindElement(By.CssSelector(".btn-add")).Click();
    driver.FindElement(By.CssSelector(".money .form-control")).Click();
    driver.FindElement(By.CssSelector(".money .form-control")).SendKeys("1000000");
    driver.FindElement(By.CssSelector(".submit")).Click();
    driver.FindElement(By.CssSelector(".print")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".print"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(1) > .form-control")).SendKeys("2024-07-06");
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(2) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(2) > .form-control")).SendKeys("0198456838");
    driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control")).SendKeys("Truyện Kiều");
    driver.FindElement(By.CssSelector(".cthd-container .col-6:nth-child(2) > .form-control")).SendKeys("10");
    driver.FindElement(By.CssSelector(".btn-add")).Click();
    driver.FindElement(By.CssSelector(".money .form-control")).Click();
    driver.FindElement(By.CssSelector(".money .form-control")).SendKeys("100000");
    driver.FindElement(By.CssSelector(".submit")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".submit"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".Toastify__toast-body")).Click();
    driver.FindElement(By.CssSelector(".exit")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector("div > .menu-bars > svg")).Click();
    driver.FindElement(By.CssSelector(".navbar-toggle")).Click();
    driver.FindElement(By.CssSelector(".nav-text:nth-child(6) .item-title")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(2) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(2) > .form-control")).SendKeys("087467242");
    driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(1) > .form-control")).SendKeys("2024-07-06");
    driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control")).SendKeys("Truyện Kiều");
    driver.FindElement(By.CssSelector(".cthd-container .col-6:nth-child(2) > .form-control")).SendKeys("10");
    driver.FindElement(By.CssSelector(".btn-add")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-add"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".money .form-control")).Click();
    driver.FindElement(By.CssSelector(".money .form-control")).SendKeys("1000000");
    driver.FindElement(By.CssSelector(".submit")).Click();
    driver.FindElement(By.CssSelector(".print")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".print"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(2) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(2) > .form-control")).SendKeys("087467242");
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".container > .row > .col-6:nth-child(1) > .form-control")).SendKeys("2024-07-06");
    driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control")).SendKeys("Truyện Kiều");
    driver.FindElement(By.CssSelector(".cthd-container .col-6:nth-child(2) > .form-control")).SendKeys("10");
    driver.FindElement(By.CssSelector(".btn-add")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-add"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".money .form-control")).Click();
    driver.FindElement(By.CssSelector(".modal")).Click();
    driver.FindElement(By.CssSelector(".cthd-container > .row > .col-6:nth-child(1) > .form-control")).SendKeys("Đắc Nhân Tâm");
    driver.FindElement(By.CssSelector(".cthd-container .col-6:nth-child(2) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".money .form-control")).Click();
    driver.FindElement(By.CssSelector(".btn-add")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-add"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".money .form-control")).Click();
    driver.FindElement(By.CssSelector(".money .form-control")).SendKeys("0");
    driver.FindElement(By.CssSelector(".submit")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(3) svg")).Click();
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(3) path:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".print")).Click();
    driver.FindElement(By.CssSelector(".form-select")).Click();
    {
      var dropdown = driver.FindElement(By.CssSelector(".form-select"));
      dropdown.FindElement(By.XPath("//option[. = 'Mã Hóa Đơn']")).Click();
    }
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).SendKeys("1");
    driver.FindElement(By.CssSelector(".btn-base")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".fa-search"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).SendKeys("2");
    driver.FindElement(By.CssSelector(".btn-base")).Click();
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).SendKeys("132");
    driver.FindElement(By.CssSelector(".btn-base")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-base"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".search-container")).Click();
    driver.FindElement(By.CssSelector(".print")).Click();
  }
}
