// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class QunlthutinTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void qunlthutin() {
    driver.Navigate().GoToUrl("http://localhost:3000/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.CssSelector("div > .menu-bars > svg")).Click();
    driver.FindElement(By.CssSelector(".nav-text:nth-child(7) .item-title")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.CssSelector(".col-12:nth-child(2) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".col-12:nth-child(2) > .form-control")).SendKeys("098567345");
    driver.FindElement(By.CssSelector(".col-12:nth-child(3) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".col-12:nth-child(3) > .form-control")).SendKeys("200000");
    driver.FindElement(By.CssSelector(".submit")).Click();
    driver.FindElement(By.CssSelector(".submit")).Click();
    driver.FindElement(By.CssSelector(".print")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".print"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.CssSelector(".col-12:nth-child(2) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".col-12:nth-child(2) > .form-control")).SendKeys("098567345");
    driver.FindElement(By.CssSelector(".col-12:nth-child(3) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".col-12:nth-child(3) > .form-control")).SendKeys("2000000");
    driver.FindElement(By.CssSelector(".submit")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".submit"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".exit")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".col-12:nth-child(2) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".col-12:nth-child(2) > .form-control")).SendKeys("0623455337");
    driver.FindElement(By.CssSelector(".col-12:nth-child(3) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".col-12:nth-child(3) > .form-control")).SendKeys("2000000");
    driver.FindElement(By.CssSelector(".submit")).Click();
    driver.FindElement(By.CssSelector(".modal-footer")).Click();
    driver.FindElement(By.CssSelector(".exit")).Click();
    driver.FindElement(By.CssSelector(".btn-detail > svg")).Click();
    driver.FindElement(By.CssSelector(".exit")).Click();
    driver.FindElement(By.CssSelector(".form-group")).Click();
    driver.FindElement(By.CssSelector(".form-select")).Click();
    {
      var dropdown = driver.FindElement(By.CssSelector(".form-select"));
      dropdown.FindElement(By.XPath("//option[. = 'Mã Phiếu']")).Click();
    }
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).SendKeys("1");
    driver.FindElement(By.CssSelector(".btn-base")).Click();
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).SendKeys("2");
    driver.FindElement(By.CssSelector(".fa-search")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".fa-search"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".Toastify__toast-body")).Click();
  }
}
