// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class QunltikhonTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void qunltikhon() {
    driver.Navigate().GoToUrl("http://localhost:3000/login");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.CssSelector(".form-control_username")).Click();
    driver.FindElement(By.CssSelector(".form-control_username")).SendKeys("present111");
    driver.FindElement(By.CssSelector(".form-control_password")).SendKeys("123");
    driver.FindElement(By.CssSelector(".btn-login")).Click();
    driver.FindElement(By.CssSelector(".navbar > div:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector("div > .menu-bars path")).Click();
    driver.FindElement(By.LinkText("QUẢN LÝ TÀI KHOẢN")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".col-6:nth-child(1) > .form-control")).SendKeys("onethrees");
    driver.FindElement(By.CssSelector(".col-6:nth-child(2) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".col-6:nth-child(2) > .form-control")).SendKeys("123");
    driver.FindElement(By.CssSelector(".form-select:nth-child(2)")).Click();
    {
      var dropdown = driver.FindElement(By.CssSelector(".form-select:nth-child(2)"));
      dropdown.FindElement(By.XPath("//option[. = 'Thủ Kho']")).Click();
    }
    driver.FindElement(By.CssSelector(".form-group:nth-child(4) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(4) > .form-control")).SendKeys("Nguyễn Văn A");
    driver.FindElement(By.CssSelector(".form-group:nth-child(5) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(5) > .form-control")).SendKeys("Thành phố Hồ Chí Minh");
    driver.FindElement(By.Name("sdt")).Click();
    driver.FindElement(By.Name("sdt")).SendKeys("01234567");
    driver.FindElement(By.CssSelector(".submit")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".col-6:nth-child(1) > .form-control")).SendKeys("onethree");
    driver.FindElement(By.CssSelector(".col-6:nth-child(2) > .form-control")).SendKeys("123");
    driver.FindElement(By.CssSelector(".form-select:nth-child(2)")).Click();
    {
      var dropdown = driver.FindElement(By.CssSelector(".form-select:nth-child(2)"));
      dropdown.FindElement(By.XPath("//option[. = 'Thủ Kho']")).Click();
    }
    driver.FindElement(By.CssSelector(".form-group:nth-child(4) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(4) > .form-control")).SendKeys("Nguyễn Văn A");
    driver.FindElement(By.CssSelector(".form-group:nth-child(5) > .form-control")).SendKeys("Thành phố Hồ Chí Minh");
    driver.FindElement(By.Name("sdt")).SendKeys("01234567");
    driver.FindElement(By.CssSelector(".submit")).Click();
    driver.FindElement(By.CssSelector(".exit")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(4) .btn-edit > svg")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(3) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(3) > .form-control")).SendKeys("Nguyễn Văn B");
    driver.FindElement(By.CssSelector(".submit")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(4) .btn-del")).Click();
    driver.FindElement(By.CssSelector(".delete")).Click();
    driver.FindElement(By.CssSelector(".form-select")).Click();
    {
      var dropdown = driver.FindElement(By.CssSelector(".form-select"));
      dropdown.FindElement(By.XPath("//option[. = 'Họ Tên']")).Click();
    }
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).SendKeys("Hoa");
    driver.FindElement(By.CssSelector(".fa-search")).Click();
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).SendKeys("Hoaa");
    driver.FindElement(By.CssSelector(".fa-search")).Click();
    driver.FindElement(By.CssSelector(".Toastify__toast-body")).Click();
  }
}
