// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class QunlnhpschTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void qunlnhpsch() {
    driver.Navigate().GoToUrl("http://localhost:3000/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.CssSelector("div > .menu-bars > svg")).Click();
    driver.FindElement(By.CssSelector(".nav-text:nth-child(5) .item-title")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-6:nth-child(1) > .form-control")).SendKeys("Truyện Kiều");
    driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-6:nth-child(1) > .form-control")).SendKeys(Keys.Enter);
    driver.FindElement(By.CssSelector(".row:nth-child(3) .form-control")).SendKeys("200");
    driver.FindElement(By.CssSelector(".btn-add")).Click();
    driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".close > span")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-6:nth-child(1) > .form-control")).SendKeys("Vì cậu là bạn nhỏ của tớ");
    driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-6:nth-child(1) > .form-control")).SendKeys(Keys.Enter);
    driver.FindElement(By.CssSelector(".exit")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-6:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-6:nth-child(1) > .form-control")).SendKeys("Đắc Nhân Tâm");
    driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-6:nth-child(1) > .form-control")).SendKeys(Keys.Enter);
    driver.FindElement(By.CssSelector(".row:nth-child(3) .form-control")).SendKeys("100");
    driver.FindElement(By.CssSelector(".btn-add")).Click();
    driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-6:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".exit")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-6:nth-child(1) > .form-control")).Click();
    driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-6:nth-child(1) > .form-control")).SendKeys("Hồng Lâu Mộng");
    driver.FindElement(By.CssSelector(".row:nth-child(1) > .col-6:nth-child(2) > .form-control")).SendKeys("Tiểu thuyết");
    driver.FindElement(By.CssSelector(".row:nth-child(2) > .col-6:nth-child(1) > .form-control")).SendKeys("Tào Tuyết Cần");
    driver.FindElement(By.CssSelector(".row:nth-child(2) > .col-6:nth-child(2) > .form-control")).SendKeys("150000");
    driver.FindElement(By.CssSelector(".row:nth-child(3) .form-control")).SendKeys("300");
    driver.FindElement(By.CssSelector(".btn-add")).Click();
    driver.FindElement(By.CssSelector(".print")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".print"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".modal-ct-pn-container .print")).Click();
    driver.FindElement(By.CssSelector(".btn-detail > svg")).Click();
    driver.FindElement(By.CssSelector(".print > svg")).Click();
    driver.FindElement(By.CssSelector(".form-select")).Click();
    {
      var dropdown = driver.FindElement(By.CssSelector(".form-select"));
      dropdown.FindElement(By.XPath("//option[. = 'Mã Phiếu']")).Click();
    }
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).SendKeys("1");
    driver.FindElement(By.CssSelector(".btn-base")).Click();
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).SendKeys("132");
    driver.FindElement(By.CssSelector(".fa-search")).Click();
    driver.FindElement(By.CssSelector(".Toastify__toast-body")).Click();
  }
}
