// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TracuschTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tracusch() {
    driver.Navigate().GoToUrl("http://localhost:3000/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    driver.FindElement(By.CssSelector("div > .menu-bars > svg")).Click();
    driver.FindElement(By.CssSelector(".nav-text:nth-child(3) .item-title")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".nav-text:nth-child(3) .item-title"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".form-select")).Click();
    {
      var dropdown = driver.FindElement(By.CssSelector(".form-select"));
      dropdown.FindElement(By.XPath("//option[. = 'Tên Sách']")).Click();
    }
    driver.FindElement(By.CssSelector(".form-control")).Click();
    driver.FindElement(By.CssSelector(".form-control")).SendKeys("doraemon");
    driver.FindElement(By.CssSelector(".fa-search")).Click();
    driver.FindElement(By.CssSelector(".Toastify__toast-body")).Click();
    driver.FindElement(By.CssSelector(".search")).Click();
    driver.FindElement(By.CssSelector(".form-control")).SendKeys("Truyện Kiều");
    driver.FindElement(By.CssSelector(".fa-search")).Click();
  }
}
