services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qlnhasach
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: huyenmyyy/backend:latest
    ports:
      - "8083:8083"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: qlnhasach
    depends_on:
      - mysql

  frontend:
    image: huyenmyyy/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
